export const CHATS_LIST = [
  {
    id: 1,
    title: 'Some Chat',
    lastMessage: "I'd like to know more about next.js",
    icon: '🦧',
    color: '#3F51B5',
    tag: 'Next.js',
    counter: 23,
    createdAt: Date.now().toString(),
  },
  {
    id: 2,
    title: 'Another Chat',
    lastMessage: 'I like your blog!',
    icon: '🐵',
    color: '#FF4081',
    tag: 'React',
    counter: 1,
    createdAt: Date.now().toString(),
  },
  {
    id: 3,
    title: 'Third Chat',
    lastMessage: 'What the f*ck is this, and what am I doing here?',
    icon: '🙈',
    color: '#FFD740',
    tag: 'React',
    counter: 999,
    createdAt: Date.now().toString(),
  },
];
